var json_data_1 = {
"type": "FeatureCollection",
"name": "data_1",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461484, "X": 117.174529, "Ketinggian": 27.0, "Foto": "images\\1.jpg", "img": "<img src=\" images\\1.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.174529, -0.461484 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.4614343, "X": 117.1743885, "Ketinggian": 30.0, "Foto": "image\\2.jpg", "img": "<img src=\" image\\2.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.1743885, -0.4614343 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461823, "X": 117.1747525, "Ketinggian": 50.0, "Foto": "image\\3.jpg", "img": "<img src=\" image\\3.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.1747525, -0.461823 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461709, "X": 117.174849, "Ketinggian": 45.0, "Foto": "image\\4.jpg", "img": "<img src=\" image\\4.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.174849, -0.461709 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.462038, "X": 117.175026, "Ketinggian": 23.0, "Foto": "image\\5.jpg", "img": "<img src=\" image\\5.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.175026, -0.462038 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461884, "X": 117.177, "Ketinggian": 39.0, "Foto": "image\\6.jpg", "img": "<img src=\" image\\6.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.177, -0.461884 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461903, "X": 117.178, "Ketinggian": 46.0, "Foto": "image\\7.jpg", "img": "<img src=\" image\\7.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.178, -0.461903 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461904, "X": 117.178, "Ketinggian": 35.0, "Foto": "image\\8.jpg", "img": "<img src=\" image\\8.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.178, -0.461904 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461848, "X": 117.178, "Ketinggian": 42.0, "Foto": "image\\9.jpg", "img": "<img src=\" image\\9.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.178, -0.461848 ] } },
{ "type": "Feature", "properties": { "Name": null, "description": null, "timestamp": null, "begin": null, "end": null, "altitudeMode": null, "tessellate": -1.0, "extrude": 0.0, "visibility": -1.0, "drawOrder": null, "icon": null, "Y": -0.461948, "X": 117.177416, "Ketinggian": 40.0, "Foto": "image\\10.jpg", "img": "<img src=\" image\\10.jpg\"\/>" }, "geometry": { "type": "Point", "coordinates": [ 117.177416, -0.461948 ] } }
]
}
